sudo: required
services: 
  - docker

before_install: 
  - docker build -t yarob50/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yarob50/react-test npm run test

after_success:
  - docker build -t yarob50/multi-client ./client
  - docker build -t yarob50/multi-nginx ./nginx
  - docker build -t yarob50/multi-server ./server
  - docker build -t yarob50/multi-worker ./worker
  # LOG IN TO THE DOCKER HUB
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER_NAME" --password-stdin
  # PUSH THE IMAGES TO YOUR ACCOUNT
  - docker push yarob50/multi-client
  - docker push yarob50/multi-nginx
  - docker push yarob50/multi-server

  - docker push yarob50/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-925342842908"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY #should be added from iam service in aws and setup as env variable in travis
  secret_access_key:
    secure: "$AWS_SECRET_KEY"