sudo: required
services: 
  - docker

before_install: 
  - docker build -t yarob50/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yarob50/react-test npm run test

after_success:
  - docker build -t yarob50/multi-client -f ./client
  - docker build -t yarob50/multi-nginx -f ./nginx
  - docker build -t yarob50/multi-server -f ./server
  - docker build -t yarob50/multi-worker -f ./worker
  # LOG IN TO THE DOCKER HUB
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER_NAME" --passwrord-stdin
  # PUSH THE IMAGES TO YOUR ACCOUNT
  - docker push yarob50/multi-client
  - docker push yarob50/multi-nginx
  - docker push yarob50/multi-server
  - docker push yarob50/multi-worker